In [1]:
import aesara.tensor as at
import numpy as np

In [2]:
A = np.array([[1,-2j],[2j,5]])
A

array([[ 1.+0.j, -0.-2.j],
       [ 0.+2.j,  5.+0.j]])

In [4]:
L = at.nlinalg.cholesky(A).eval()
L

array([[1.+0.j, 0.+0.j],
       [0.+2.j, 1.+0.j]])

In [5]:
np.dot(L, L.T.conj()) # verify that L * L.H = A

array([[1.+0.j, 0.-2.j],
       [0.+2.j, 5.+0.j]])

In [6]:
A = [[1,-2j],[2j,5]] # what happens if A is only array_like?

In [7]:
at.nlinalg.cholesky(A).eval() # an ndarray object is returned

array([[1.+0.j, 0.+0.j],
       [0.+2.j, 1.+0.j]])

In [8]:
# But a matrix object is returned if A is a matrix object
at.nlinalg.cholesky(np.matrix(A)).eval()

matrix([[1.+0.j, 0.+0.j],
        [0.+2.j, 1.+0.j]])