In [1]:
import aesara.tensor as at
import numpy as np

WARNING (aesara.tensor.blas): Using NumPy C-API based implementation for BLAS functions.


In [2]:
d1 = np.arange(1,4)
d2 = np.arange(1,10).reshape(3,3)
d3 = np.arange(1,19).reshape(2,3,3)

d1.shape, d2.shape, d3.shape

((3,), (3, 3), (2, 3, 3))

In [8]:
#tril
print(np.allclose(at.tril(d1).eval(), np.tril(d1)))
print(np.allclose(at.tril(d2).eval(), np.tril(d2)))
print(np.allclose(at.tril(d3).eval(), np.tril(d3)))

True
True
True


In [7]:
#triu
print(np.allclose(at.triu(d1).eval(), np.triu(d1)))
print(np.allclose(at.triu(d2).eval(), np.triu(d2)))
print(np.allclose(at.triu(d3).eval(), np.triu(d3)))

True
True
True


In [6]:
#diag
print(np.allclose(at.diag(d1).eval(), np.diag(d1)))
print(np.allclose(at.diag(d2).eval(), np.diag(d2)))

True
True


In [9]:
at.diag(d3).eval()

array([[ 1, 13],
       [ 2, 14],
       [ 3, 15]])

In [10]:
np.diag(d3).eval()

ValueError: Input must be 1- or 2-d.

In [12]:
from tests.tensor.utils import random_of_dtype
m = random_of_dtype((10,), "int32")
m

array([ 4,  3, -3,  1, -5,  0, -2,  1,  0, -2])

In [15]:
np.triu_indices_from(d1)

ValueError: input array must be 2-d

In [16]:
at.triu_indices_from(d2)

(Nonzero.0, Nonzero.1)

In [18]:
at.triu_indices_from(d1)

ValueError: The input array must be two dimensional.

In [20]:
at.tril(np.arange(3*4*5).reshape(3, 4, 5)).eval()

array([[[ 0,  0,  0,  0,  0],
        [ 5,  6,  0,  0,  0],
        [10, 11, 12,  0,  0],
        [15, 16, 17, 18,  0]],

       [[20,  0,  0,  0,  0],
        [25, 26,  0,  0,  0],
        [30, 31, 32,  0,  0],
        [35, 36, 37, 38,  0]],

       [[40,  0,  0,  0,  0],
        [45, 46,  0,  0,  0],
        [50, 51, 52,  0,  0],
        [55, 56, 57, 58,  0]]])

In [24]:
at.tril(np.arange(1,13).reshape(4,3), -1).eval()

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [25]:
at.triu(np.arange(1,13).reshape(4,3), -1).eval()

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [26]:
at.triu(np.arange(3*4*5).reshape(3, 4, 5)).eval()

array([[[ 0,  1,  2,  3,  4],
        [ 0,  6,  7,  8,  9],
        [ 0,  0, 12, 13, 14],
        [ 0,  0,  0, 18, 19]],

       [[20, 21, 22, 23, 24],
        [ 0, 26, 27, 28, 29],
        [ 0,  0, 32, 33, 34],
        [ 0,  0,  0, 38, 39]],

       [[40, 41, 42, 43, 44],
        [ 0, 46, 47, 48, 49],
        [ 0,  0, 52, 53, 54],
        [ 0,  0,  0, 58, 59]]])