In [1]:
import pymc as pm
import numpy as np

In [3]:
# Parameters
#     ----------
#     mu: array
#         Vector of means, just as in `MvNormal`.
#     covs: list of arrays
#         The set of covariance matrices :math:`[K_1, K_2, ...]` to be
#         Kroneckered in the order provided :math:`\bigotimes K_i`.
#     chols: list of arrays
#         The set of lower cholesky matrices :math:`[L_1, L_2, ...]` such that
#         :math:`K_i = L_i L_i'`.
#     evds: list of tuples
#         The set of eigenvalue-vector, eigenvector-matrix pairs
#         :math:`[(v_1, Q_1), (v_2, Q_2), ...]` such that
#         :math:`K_i = Q_i \text{diag}(v_i) Q_i'`. For example::

#             v_i, Q_i = at.nlinalg.eigh(K_i)

#     sigma: scalar, variable
#         Standard deviation of the Gaussian white noise.

In [15]:
K1 = np.array([[1., 0.5, 1.0], [0.5, 2, 10.0]])
K2 = np.array([[1., 0.4, 0.2], [0.4, 2, 0.3], [0.2, 0.3, 1]])
covs = [K1, K2, K1, K2]

pm.KroneckerNormal.dist(mu=np.zeros(6), covs=covs)

kroneckernormal_rv{1, (1, 0, 2), floatX, False}.out

In [19]:
pm.KroneckerNormal.dist(mu=np.zeros(6), covs=covs)

kroneckernormal_rv{1, (1, 0, 2), floatX, False}.out

In [20]:
pm.KroneckerNormal.dist(mu=np.zeros(6), chols=covs)

kroneckernormal_rv{1, (1, 0, 2), floatX, False}.out

In [22]:
covs

[array([[ 1. ,  0.5,  1. ],
        [ 0.5,  2. , 10. ]]),
 array([[1. , 0.4, 0.2],
        [0.4, 2. , 0.3],
        [0.2, 0.3, 1. ]]),
 array([[ 1. ,  0.5,  1. ],
        [ 0.5,  2. , 10. ]]),
 array([[1. , 0.4, 0.2],
        [0.4, 2. , 0.3],
        [0.2, 0.3, 1. ]])]