In [3]:
import pymc as pm
import numpy as np

In [1]:
# Parameters
#     ----------
#     mu: array
#         Array of means. Must be broadcastable with the random variable X such
#         that the shape of mu + X is (m,n).
#     rowcov: mxm array
#         Among-row covariance matrix. Defines variance within
#         columns. Exactly one of rowcov or rowchol is needed.
#     rowchol: mxm array
#         Cholesky decomposition of among-row covariance matrix. Exactly one of
#         rowcov or rowchol is needed.
#     colcov: nxn array
#         Among-column covariance matrix. If rowcov is the identity matrix,
#         this functions as `cov` in MvNormal.
#         Exactly one of colcov or colchol is needed.
#     colchol: nxn array
#         Cholesky decomposition of among-column covariance matrix. Exactly one
#         of colcov or colchol is needed.

In [4]:
colcov = np.array([[1., 0.5], [0.5, 2]])
rowcov = np.array([[1, 0, 0], [0, 4, 0], [0, 0, 16]])

In [6]:
m = rowcov.shape[0]
n = colcov.shape[0]

m, n

(3, 2)

In [7]:
mu = np.zeros((m, n))
mu

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
vals = pm.MatrixNormal.dist(mu=mu, colcov=colcov, rowcov=rowcov)

In [11]:
vals

matrixnormal_rv{2, (2, 2, 2), floatX, False}.out

In [13]:
colcov = np.ones((2,2,2))
colcov

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [14]:
rowcov = np.ones((3,3,3))
rowcov

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
mu = np.zeros((3, 2))
mu

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
pm.MatrixNormal.dist(mu=mu, colcov=colcov, rowcov=rowcov)

ValueError: rowcov must be two dimensional.