## Checking Ops for MvNormal

- mu -> works for nd Data
- cov, tau, chol -> works for 2D data only

In [6]:
import pymc as pm
import numpy as np

In [57]:
with pm.Model():
    x = pm.Normal('x', mu=0, sigma=10)

In [3]:
x

x ~ N(0, 10)

In [30]:
np.ones(2)

array([1., 1.])

In [32]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [28]:
#Example given in Issue: https://github.com/pymc-devs/pymc/issues/5383

# size = (4, 3)
# pm.logp(pm.MvNormal.dist(mu=np.ones(2), cov=np.eye(2), size=size), np.ones((*size, 2)))
# ValueError: Invalid dimension for value: 3

# pm.logp(pm.MvStudentT.dist(nu=3, mu=np.ones(2), cov=np.eye(2), size=size), np.ones((*size, 2)))
# ValueError: Invalid dimension for value: 3

## Checking for mu
### 1. 2D --> Pass

In [34]:
pm.MvNormal.dist(mu=np.ones((2,2)), cov=np.ones((2,2)))

multivariate_normal_rv{1, (1, 2), floatX, False}.out

### 2. 3D --> Pass

In [59]:
pm.MvNormal.dist(mu=np.ones((10,2,2)), cov=np.ones((2,2)))

multivariate_normal_rv{1, (1, 2), floatX, False}.out

### 3. nD --> Pass

In [53]:
pm.MvNormal.dist(mu=np.ones((2,2,2,2,2)), cov=np.ones((2,2)))

multivariate_normal_rv{1, (1, 2), floatX, False}.out

## Checking for cov
### 1. 2D --> Pass

In [45]:
pm.MvNormal.dist(mu=np.ones(2), cov=np.ones((2,2)))

multivariate_normal_rv{1, (1, 2), floatX, False}.out

### 2. 3D --> Fail

In [46]:
pm.MvNormal.dist(mu=np.ones(2), cov=np.ones((2,2,2)))

ValueError: cov must be two dimensional.

## Checking for tau
### 1. 2D --> Pass

In [48]:
pm.MvNormal.dist(mu=np.ones(2), tau=np.ones((2,2)))

multivariate_normal_rv{1, (1, 2), floatX, False}.out

### 2. 3D --> Fail

In [49]:
pm.MvNormal.dist(mu=np.ones(2), tau=np.ones((2,2,2)))

ValueError: tau must be two dimensional.

In [54]:
pm.MvNormal.dist(mu=np.ones(2), chol=np.ones((2,2)))

multivariate_normal_rv{1, (1, 2), floatX, False}.out

In [55]:
pm.MvNormal.dist(mu=np.ones(2), chol=np.ones((2,2,2)))

ValueError: chol must be two dimensional.