In [1]:
import aesara.tensor as at
import numpy as np

#### Solve the system of equations 
``x0 + 2 * x1 = 1``

``3 * x0 + 5 * x1 = 2``

### Float data - No Error

In [2]:
a = np.array([[1, 2], [3, 5]], dtype = 'float64')
b = np.array([1, 2], dtype = 'float64')

In [3]:
# Numpy solve
np.linalg.solve(a, b)

array([-1.,  1.])

In [4]:
#Aesara Scipy solve
at.slinalg.solve(a, b).eval()

array([-1.,  1.])

In [5]:
#Aesara Numpy solve
at.nlinalg.solve(a, b).eval()

array([-1.,  1.])

### Int data

In [6]:
a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])

In [7]:
# Numpy solve
np.linalg.solve(a, b)

array([-1.,  1.])

In [8]:
#Aesara Scipy solve
at.slinalg.solve(a, b).eval()

array([-1.,  1.])

In [9]:
#Aesara Numpy solve
at.nlinalg.solve(a, b).eval()

ERROR (aesara.graph.opt): Optimization failure due to: constant_folding
ERROR (aesara.graph.opt): node: Solve(TensorConstant{[[1 2]
 [3 5]]}, TensorConstant{[1 2]})
ERROR (aesara.graph.opt): TRACEBACK:
ERROR (aesara.graph.opt): Traceback (most recent call last):
  File "D:\OpenSource\aesara\aesara\graph\opt.py", line 1861, in process_node
    replacements = lopt.transform(fgraph, node)
  File "D:\OpenSource\aesara\aesara\graph\opt.py", line 1066, in transform
    return self.fn(fgraph, node)
  File "D:\OpenSource\aesara\aesara\tensor\basic_opt.py", line 2807, in constant_folding
    v = output_type.make_constant(data)
  File "D:\OpenSource\aesara\aesara\graph\type.py", line 213, in make_constant
    return self.constant_type(type=self, data=value, name=name)
  File "D:\OpenSource\aesara\aesara\tensor\var.py", line 1011, in __init__
    Constant.__init__(self, new_type, data, name)
  File "D:\OpenSource\aesara\aesara\graph\basic.py", line 729, in __init__
    self.data = type.filter(dat

array([-1.,  1.])