In [1]:
import numpy as np
import aesara.tensor as at
from aesara.tensor.type import matrix, tensor3
import aesara

### Creating int array

In [3]:
a = np.full((2,3,3), np.eye(3), dtype = "int32")
b = np.arange(2*3).reshape(2,3)

a.dtype, b.dtype

(dtype('int32'), dtype('int32'))

# Calse - 1:
#### Infer dtype by solving the most simple case with 1x1 matrices
```
out_dtype = np.linalg.solve(
    np.eye(1).astype(a.dtype), np.eye(1).astype(b.dtype)
).dtype
```

### 1. Compile graph using aesara.function - No Error

In [8]:
A = tensor3()
B = matrix()
y = at.nlinalg.solve(A, B)
f = aesara.function([A, B], y)

f(a ,b)

array([[0., 1., 2.],
       [3., 4., 5.]])

### 2. Compile graph using eval() - No Error

In [9]:
at.nlinalg.solve(a, b).eval()

array([[0., 1., 2.],
       [3., 4., 5.]])

# Calse - 2:
#### Infer dtype by using aesara.scalar.upcast
```
out_dtype = aes.upcast(a.dtype, b.dtype)
```

### 2.1. Compile graph using aesara.function - No Error

In [4]:
A = tensor3()
B = matrix()
y = at.nlinalg.solve(A, B)
f = aesara.function([A, B], y)

f(a ,b)

array([[0., 1., 2.],
       [3., 4., 5.]])

### 2.2. Compile graph using eval() - Optimization Error

In [5]:
at.nlinalg.solve(a, b).eval()

ERROR (aesara.graph.opt): Optimization failure due to: constant_folding
ERROR (aesara.graph.opt): node: Solve(TensorConstant{[[[1 0 0]
.. [0 0 1]]]}, TensorConstant{[[0 1 2]
 [3 4 5]]})
ERROR (aesara.graph.opt): TRACEBACK:
ERROR (aesara.graph.opt): Traceback (most recent call last):
  File "D:\OpenSource\aesara\aesara\graph\opt.py", line 1861, in process_node
    replacements = lopt.transform(fgraph, node)
  File "D:\OpenSource\aesara\aesara\graph\opt.py", line 1066, in transform
    return self.fn(fgraph, node)
  File "D:\OpenSource\aesara\aesara\tensor\basic_opt.py", line 2807, in constant_folding
    v = output_type.make_constant(data)
  File "D:\OpenSource\aesara\aesara\graph\type.py", line 213, in make_constant
    return self.constant_type(type=self, data=value, name=name)
  File "D:\OpenSource\aesara\aesara\tensor\var.py", line 1011, in __init__
    Constant.__init__(self, new_type, data, name)
  File "D:\OpenSource\aesara\aesara\graph\basic.py", line 729, in __init__
    self.d

array([[0., 1., 2.],
       [3., 4., 5.]])