In [17]:
import pymc as pm
import numpy as np

### alpha - scalar

In [18]:
K = 4
alpha = 0.5
value = np.array([5, 4, 3, 2, 1]) / 15

pm.logp(pm.StickBreakingWeights.dist(alpha=alpha, K=K), value).eval()

array(1.51263013)

### alpha - 1D Array

In [19]:
K = 4
alpha = [0.5, 1, 2, 3]
value = np.array([5, 4, 3, 2, 1]) / 15

pm.logp(pm.StickBreakingWeights.dist(alpha=alpha, K=K), value).eval()

array([1.51263013, 2.93119375, 2.99573227, 1.9095425 ])

### alpha - 2D Array

In [20]:
K = 4
alpha = np.arange(1, 13).reshape(3, 4)
value = np.array([5, 4, 3, 2, 1]) / 15

pm.logp(pm.StickBreakingWeights.dist(alpha=alpha, K=K), value).eval()

array([[  2.93119375,   2.99573227,   1.9095425 ,   0.35222059],
       [ -1.4632554 ,  -3.44201938,  -5.53346686,  -7.70739149],
       [ -9.94430955, -12.23091769, -14.55772717, -16.91773186]])

### alpha - 3D Array

In [35]:
K = 4
alpha = np.arange(1, 2*3*4+1).reshape(2, 3, 4)
value = np.array([5, 4, 3, 2, 1]) / 15

pm.logp(pm.StickBreakingWeights.dist(alpha=alpha, K=K), value).eval()

array([[[  2.93119375,   2.99573227,   1.9095425 ,   0.35222059],
        [ -1.4632554 ,  -3.44201938,  -5.53346686,  -7.70739149],
        [ -9.94430955, -12.23091769, -14.55772717, -16.91773186]],

       [[-19.30561123, -21.71722954, -24.14930826, -26.59920438],
        [-29.06475609, -31.54417263, -34.03595395, -36.53883097],
        [-39.05172052, -41.57369066, -44.10393381, -46.64174555]]])