## Results
Below Ops are not supporting batched data
1. at.linalg.det
2. at.linalg.eigh
3. matrix_inverse
4. cholesky


- np.diag -> fails with batched data
- np.matrix.trace -> give sum of every diag in a list but aesara give total sum 
- np.fill_diagonal -> inplace operation and doesn't return anything but aesara return the data

- at.or_ , np.logical_or -> different behavior
- at.and_, np.logical_and

In [146]:
import numpy as np
import aesara.tensor as at

In [147]:
d2 = np.full((3,3), np.eye(3))
d3 = np.full((2,3,3), np.eye(3))
d2.shape, d3.shape

((3, 3), (2, 3, 3))

In [148]:
x1 = np.arange(3*3).reshape(3,3)
x2 = np.arange(1*2*3).reshape(1,2,3)
x3 = np.arange(1*2*3*4).reshape(1,2,3,4)

## at.broadcast_arrays

In [151]:
x = np.array([[1,2,3]])
y = np.array([[4],[5]])

#### Deprecated in numpy since version 1.17:

In [152]:
np.broadcast_arrays(x, y)

[array([[1, 2, 3],
        [1, 2, 3]]),
 array([[4, 4, 4],
        [5, 5, 5]])]

In [159]:
at.broadcast_arrays(x, y)

(BroadcastTo.0, BroadcastTo.0)

In [153]:
at.broadcast_arrays(x, y)[0].eval()

array([[1, 2, 3],
       [1, 2, 3]])

In [155]:
at.broadcast_arrays(x, y)[1].eval()

array([[4, 4, 4],
       [5, 5, 5]])

## at.concatenate

In [58]:
np.allclose(np.concatenate([x3, x3]), at.concatenate([x3, x3]).eval())

True

In [13]:
at.concatenate([d3, d3]).eval()

array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]])

## at.full

In [59]:
np.allclose(np.full((2,2,2), 1), at.full((2,2,2), 1).eval())

True

In [60]:
at.full((2,2,2), 1).eval()

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int8)

## at.diag

In [54]:
np.allclose(np.diag(d2), at.diag(d2).eval())

True

In [53]:
at.diag(d3).eval()

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [56]:
# Numpy fails on batched data
np.diag(d3)

ValueError: Input must be 1- or 2-d.

## at.all

In [61]:
np.allclose(np.all(x3), at.all(x3).eval())

True

In [22]:
at.all(d3).eval()

array(False)

## at.sum

In [63]:
np.allclose(np.sum(x3), at.sum(x3).eval())

True

In [25]:
at.sum(d3).eval()

array(6.)

## at.log

In [71]:
np.allclose(np.log(d3), at.log(d3).eval())

C:\Users\Purna\AppData\Local\Temp\ipykernel_8680\1408697670.py:1: RuntimeWarning: divide by zero encountered in log
  np.allclose(np.log(d3), at.log(d3).eval())


True

In [66]:
at.log(d3).eval()

array([[[  0., -inf, -inf],
        [-inf,   0., -inf],
        [-inf, -inf,   0.]],

       [[  0., -inf, -inf],
        [-inf,   0., -inf],
        [-inf, -inf,   0.]]])

## at.dot

In [73]:
np.allclose(np.dot(x2, x3), at.dot(x2, x3).eval())

True

In [29]:
at.dot(d2, d3).eval()

array([[[1., 0., 0.],
        [1., 0., 0.]],

       [[0., 1., 0.],
        [0., 1., 0.]],

       [[0., 0., 1.],
        [0., 0., 1.]]])

## aesara.tensor.gammaln

In [141]:
import scipy

In [142]:
np.allclose(scipy.special.gammaln(x3), at.gammaln(x3).eval())

True

In [30]:
at.gammaln(d3).eval()

array([[[ 0., inf, inf],
        [inf,  0., inf],
        [inf, inf,  0.]],

       [[ 0., inf, inf],
        [inf,  0., inf],
        [inf, inf,  0.]]])

## at.log1p

In [79]:
np.allclose(np.log1p(x3), at.log1p(x3).eval())

True

In [31]:
at.log1p(d3).eval()

array([[[0.69314718, 0.        , 0.        ],
        [0.        , 0.69314718, 0.        ],
        [0.        , 0.        , 0.69314718]],

       [[0.69314718, 0.        , 0.        ],
        [0.        , 0.69314718, 0.        ],
        [0.        , 0.        , 0.69314718]]])

## at.transpose

In [28]:
at.transpose(d3).eval()

array([[[1., 1.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [1., 1.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [1., 1.]]])

In [29]:
np.transpose(d3)

array([[[1., 1.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [1., 1.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [1., 1.]]])

In [30]:
np.allclose(np.transpose(d3), at.transpose(d3).eval())

True

In [31]:
x1 = np.arange(3*3).reshape(3,3)
x2 = np.arange(1*2*3).reshape(1,2,3)
x3 = np.arange(1*2*3*4).reshape(1,2,3,4)

In [32]:
np.allclose(np.transpose(x1), at.transpose(x1).eval())

True

In [33]:
np.allclose(np.transpose(x2), at.transpose(x2).eval())

True

In [34]:
np.allclose(np.transpose(x2), at.transpose(x2).eval())

True

# at.sqrt

In [80]:
np.allclose(np.sqrt(x3), at.sqrt(x3).eval())

True

In [34]:
at.sqrt(d3).eval()

array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]])

## at.batched_dot

In [82]:
# batched_dot doesn't present in numpy
at.batched_dot(d3, d3).eval()

array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]])

## at.full_like

In [83]:
np.allclose(np.full_like(d3, 1), at.full_like(d3, 1).eval())

True

In [51]:
at.full_like(d3, 1).eval()

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int8)

## at.nlinalg.matrix_dot

In [87]:
np.allclose(np.matrix.dot(d3, d3), at.nlinalg.matrix_dot(d3, d3).eval())

True

In [84]:
at.nlinalg.matrix_dot(d2, d3).eval()

array([[[1., 0., 0.],
        [1., 0., 0.]],

       [[0., 1., 0.],
        [0., 1., 0.]],

       [[0., 0., 1.],
        [0., 0., 1.]]])

## at.nlinalg.trace

In [91]:
np.allclose(np.matrix.trace(d3), at.nlinalg.trace(d3).eval())

False

In [162]:
np.matrix.trace(d3)

array([1., 1., 0.])

In [93]:
np.matrix.trace(d3).sum()

2.0

In [164]:
x3.shape

(1, 2, 3, 4)

In [166]:
np.matrix.trace(x3)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [167]:
at.nlinalg.trace(x3).eval()

array(66, dtype=int64)

In [94]:
np.allclose(np.matrix.trace(x3).sum(), at.nlinalg.trace(x3).eval())

True

In [55]:
at.nlinalg.trace(d3).eval()

array(2.)

## at.zeros_like

In [96]:
np.allclose(np.zeros_like(d3), at.zeros_like(d3).eval())

True

In [57]:
at.zeros_like(d3).eval()

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## at.take

In [98]:
np.allclose(np.take(x3, [0,1,2]), at.take(x3, [0,1,2]).eval())

True

In [60]:
at.take(d3, [0,1,2]).eval()

array([1., 0., 0.])

## at.fill_diagonal

In [105]:
a = np.zeros((3, 3, 3))
b = np.zeros((3, 3, 3))
np.fill_diagonal(a, 4)
np.allclose(a, at.fill_diagonal(b, 4).eval())

True

In [168]:
a = np.zeros((3, 3, 3))
np.fill_diagonal(a, 4)

In [169]:
a

array([[[4., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 4., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 4.]]])

In [170]:
a = np.zeros((3, 3, 3))
at.fill_diagonal(a, 4).eval()

array([[[4., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 4., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 4.]]])

## at.linalg.det

In [107]:
np.linalg.det(d3)

array([1., 1.])

In [109]:
np.allclose(np.linalg.det(d2), at.linalg.det(d2).eval())

True

In [89]:
at.linalg.det(d3).eval()

AssertionError: 

## at.cumsum

In [111]:
np.allclose(np.cumsum(d3), at.cumsum(d3).eval())

True

In [92]:
at.cumsum(d3).eval()

array([1., 1., 1., 1., 2., 2., 2., 2., 3., 4., 4., 4., 4., 5., 5., 5., 5.,
       6.])

## at.zeros

In [112]:
np.allclose(np.zeros((2,3,3)), at.zeros((2,3,3)).eval())

True

In [95]:
at.zeros((2,3,3)).eval()

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## at.sqrt

In [114]:
np.allclose(np.sqrt(x3), at.sqrt(x3).eval())

True

In [99]:
at.sqrt(d3).eval()

array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]])

## at.or_

In [124]:
a = np.zeros((2, 2, 2), int)
b = np.ones((2, 2, 2), int) * 3

In [125]:
np.logical_or(a, b)

array([[[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [128]:
at.or_(a,b).eval()

array([[[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]]])

## at.and_

In [130]:
np.logical_and(a, b)

array([[[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])

In [129]:
at.and_(a, b).eval()

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

## at.le

In [135]:
np.allclose(np.ndarray.__le__(a,b), at.le(a,b).eval())

True

In [111]:
at.le(a,b).eval()

array([[[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

# at.ge

In [136]:
np.allclose(np.ndarray.__ge__(a,b), at.ge(a,b).eval())

True

In [112]:
at.ge(a, b).eval()

array([[[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])

## at.neq

In [137]:
np.allclose(np.not_equal(a,b), at.neq(a, b).eval())

True

In [115]:
at.neq(a, b).eval()

array([[[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

## at.any

In [138]:
np.allclose(np.any(d3), at.any(d3).eval())

True

In [118]:
at.any(d3).eval()

array(True)

## at.allclose

In [119]:
at.allclose(d3, d3).eval()

array(True)

## at.sigmoid

In [143]:
np.allclose(scipy.special.expit(d3), at.sigmoid(d3).eval())

True

In [124]:
at.sigmoid(d3).eval()

array([[[0.73105858, 0.5       , 0.5       ],
        [0.5       , 0.73105858, 0.5       ],
        [0.5       , 0.5       , 0.73105858]],

       [[0.73105858, 0.5       , 0.5       ],
        [0.5       , 0.73105858, 0.5       ],
        [0.5       , 0.5       , 0.73105858]]])

## at.nlinalg.eigh

In [145]:
at.nlinalg.eigh(d2)

[Eigh{UPLO='L'}.0, Eigh{UPLO='L'}.1]

In [130]:
at.nlinalg.eigh(d3)

AssertionError: 