## Results
Below Ops are not supporting batched data
1. at.linalg.det
2. at.linalg.eigh
3. matrix_inverse
4. cholesky

In [2]:
import numpy as np
import aesara.tensor as at

In [15]:
d2 = np.full((3,3), np.eye(3))
d3 = np.full((2,3,3), np.eye(3))
d2.shape, d3.shape

((3, 3), (2, 3, 3))

## at.broadcast_arrays

In [7]:
at.broadcast_arrays(d2, d3)

(BroadcastTo.0, BroadcastTo.0)

## at.concatenate

In [13]:
at.concatenate([d3, d3]).eval()

array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]])

## at.full

In [19]:
at.full((2,2,2), 1).eval()

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int8)

## at.diag

In [20]:
at.diag(d3).eval()

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

## at.all

In [22]:
at.all(d3).eval()

array(False)

## at.sum

In [25]:
at.sum(d3).eval()

array(6.)

## at.log

In [27]:
at.log(d3).eval()

array([[[  0., -inf, -inf],
        [-inf,   0., -inf],
        [-inf, -inf,   0.]],

       [[  0., -inf, -inf],
        [-inf,   0., -inf],
        [-inf, -inf,   0.]]])

## at.dot

In [29]:
at.dot(d2, d3).eval()

array([[[1., 0., 0.],
        [1., 0., 0.]],

       [[0., 1., 0.],
        [0., 1., 0.]],

       [[0., 0., 1.],
        [0., 0., 1.]]])

## aesara.tensor.gammaln

In [30]:
at.gammaln(d3).eval()

array([[[ 0., inf, inf],
        [inf,  0., inf],
        [inf, inf,  0.]],

       [[ 0., inf, inf],
        [inf,  0., inf],
        [inf, inf,  0.]]])

## at.log1p

In [31]:
at.log1p(d3).eval()

array([[[0.69314718, 0.        , 0.        ],
        [0.        , 0.69314718, 0.        ],
        [0.        , 0.        , 0.69314718]],

       [[0.69314718, 0.        , 0.        ],
        [0.        , 0.69314718, 0.        ],
        [0.        , 0.        , 0.69314718]]])

## at.transpose

In [16]:
at.transpose(d3).eval()

array([[[1., 1.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [1., 1.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [1., 1.]]])

In [17]:
np.allclose(np.transpose(d3), at.transpose(d3).eval())

True

In [20]:
x1 = np.arange(3*3).reshape(3,3)
x2 = np.arange(1*2*3).reshape(3,3)
x3 = np.arange(1*2*3*4).reshape(3,3)

In [11]:
np.allclose(np.transpose(x1), at.transpose(x1).eval())

True

In [12]:
np.allclose(np.transpose(x2), at.transpose(x2).eval())

True

In [13]:
np.allclose(np.transpose(x2), at.transpose(x2).eval())

True

# at.sqrt

In [34]:
at.sqrt(d3).eval()

array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]])

## at.batched_dot

In [48]:
at.batched_dot(d3, d3).eval()

array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]])

## at.full_like

In [51]:
at.full_like(d3, 1).eval()

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int8)

## at.nlinalg.matrix_dot

In [53]:
at.nlinalg.matrix_dot(d3, d3).eval()

array([[[[1., 0., 0.],
         [1., 0., 0.]],

        [[0., 1., 0.],
         [0., 1., 0.]],

        [[0., 0., 1.],
         [0., 0., 1.]]],


       [[[1., 0., 0.],
         [1., 0., 0.]],

        [[0., 1., 0.],
         [0., 1., 0.]],

        [[0., 0., 1.],
         [0., 0., 1.]]]])

## at.nlinalg.trace

In [55]:
at.nlinalg.trace(d3).eval()

array(2.)

## at.zeros_like

In [57]:
at.zeros_like(d3).eval()

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## at.take

In [60]:
at.take(d3, [0,1,2]).eval()

array([1., 0., 0.])

## at.fill_diagonal

In [65]:
at.fill_diagonal(d2, 3).eval()

array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 3.]])

In [79]:
a = np.zeros((3, 3, 3))
at.fill_diagonal(a, 4).eval()

array([[[4., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 4., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 4.]]])

## at.linalg.det

In [89]:
at.linalg.det(d3).eval()

AssertionError: 

## at.cumsum

In [92]:
at.cumsum(d3).eval()

array([1., 1., 1., 1., 2., 2., 2., 2., 3., 4., 4., 4., 4., 5., 5., 5., 5.,
       6.])

## at.zeros

In [95]:
at.zeros((2,3,3)).eval()

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## at.sqrt

In [99]:
at.sqrt(d3).eval()

array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]],

       [[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]])

## at.or_

In [107]:
a = np.zeros((2, 2, 2), int)
b = np.ones((2, 2, 2), int)

In [108]:
at.or_(a,b).eval()

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

## at.and_

In [109]:
at.and_(a, b).eval()

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

## at.le

In [111]:
at.le(a,b).eval()

array([[[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

# at.ge

In [112]:
at.ge(a, b).eval()

array([[[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])

## at.neq

In [115]:
at.neq(a, b).eval()

array([[[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

## at.any

In [118]:
at.any(d3).eval()

array(True)

## at.allclose

In [119]:
at.allclose(d3, d3).eval()

array(True)

## at.sigmoid

In [124]:
at.sigmoid(d3).eval()

array([[[0.73105858, 0.5       , 0.5       ],
        [0.5       , 0.73105858, 0.5       ],
        [0.5       , 0.5       , 0.73105858]],

       [[0.73105858, 0.5       , 0.5       ],
        [0.5       , 0.73105858, 0.5       ],
        [0.5       , 0.5       , 0.73105858]]])

## at.nlinalg.eigh

In [129]:
at.nlinalg.eigh(d2)

[Eigh{UPLO='L'}.0, Eigh{UPLO='L'}.1]

In [130]:
at.nlinalg.eigh(d3)

AssertionError: 

## at.nlinalg.trace

In [132]:
at.nlinalg.trace(d3).eval()

array(2.)