In [1]:
import numpy as np
import aesara.tensor as at

WARN: Could not locate executable g77
WARN: Could not locate executable f77
WARN: Could not locate executable ifort
WARN: Could not locate executable ifl
WARN: Could not locate executable f90
WARN: Could not locate executable DF
WARN: Could not locate executable efl


In [2]:
A2 = np.array([[6, 3, 4, 8], [3, 6, 5, 1], [4, 5, 10, 7], [8, 1, 7, 25]])
A2.shape

(4, 4)

## Aesara Scipy Cholesky with np.vectorize

In [3]:
at.linalg.cholesky(A2).eval()

NP Vectorize...


array([[2, 1, 2, 2],
       [1, 2, 2, 1],
       [2, 2, 3, 2],
       [2, 1, 2, 5]])

In [4]:
A3 = np.array([A2, A2])
A3.shape

(2, 4, 4)

In [5]:
at.linalg.cholesky(A3).eval()

NP Vectorize...


array([[[2, 1, 2, 2],
        [1, 2, 2, 1],
        [2, 2, 3, 2],
        [2, 1, 2, 5]],

       [[2, 1, 2, 2],
        [1, 2, 2, 1],
        [2, 2, 3, 2],
        [2, 1, 2, 5]]])

## Aesara-Numpy Cholesky

In [6]:
at.linalg.cholesky_np(A2).eval()

array([[ 2,  0,  0,  0],
       [ 1,  2,  0,  0],
       [ 1,  1,  2,  0],
       [ 3, -1,  1,  3]])

In [7]:
at.linalg.cholesky_np(A3).eval()

array([[[ 2,  0,  0,  0],
        [ 1,  2,  0,  0],
        [ 1,  1,  2,  0],
        [ 3, -1,  1,  3]],

       [[ 2,  0,  0,  0],
        [ 1,  2,  0,  0],
        [ 1,  1,  2,  0],
        [ 3, -1,  1,  3]]])

## Scipy Cholesky

In [8]:
import scipy

In [9]:
scipy.linalg.cholesky(A2, lower=True)

array([[ 2.44948974,  0.        ,  0.        ,  0.        ],
       [ 1.22474487,  2.12132034,  0.        ,  0.        ],
       [ 1.63299316,  1.41421356,  2.30940108,  0.        ],
       [ 3.26598632, -1.41421356,  1.58771324,  3.13249102]])

In [10]:
vfun = np.vectorize(scipy.linalg.cholesky)
vfun(A3)

array([[[2.44948974, 1.73205081, 2.        , 2.82842712],
        [1.73205081, 2.44948974, 2.23606798, 1.        ],
        [2.        , 2.23606798, 3.16227766, 2.64575131],
        [2.82842712, 1.        , 2.64575131, 5.        ]],

       [[2.44948974, 1.73205081, 2.        , 2.82842712],
        [1.73205081, 2.44948974, 2.23606798, 1.        ],
        [2.        , 2.23606798, 3.16227766, 2.64575131],
        [2.82842712, 1.        , 2.64575131, 5.        ]]])

## Numpy Cholesky

In [11]:
np.linalg.cholesky(A2)

array([[ 2.44948974,  0.        ,  0.        ,  0.        ],
       [ 1.22474487,  2.12132034,  0.        ,  0.        ],
       [ 1.63299316,  1.41421356,  2.30940108,  0.        ],
       [ 3.26598632, -1.41421356,  1.58771324,  3.13249102]])

In [12]:
np.linalg.cholesky(A3)

array([[[ 2.44948974,  0.        ,  0.        ,  0.        ],
        [ 1.22474487,  2.12132034,  0.        ,  0.        ],
        [ 1.63299316,  1.41421356,  2.30940108,  0.        ],
        [ 3.26598632, -1.41421356,  1.58771324,  3.13249102]],

       [[ 2.44948974,  0.        ,  0.        ,  0.        ],
        [ 1.22474487,  2.12132034,  0.        ,  0.        ],
        [ 1.63299316,  1.41421356,  2.30940108,  0.        ],
        [ 3.26598632, -1.41421356,  1.58771324,  3.13249102]]])

## Testing diff cholesky

In [13]:
# Aesara scipy with vectorization vs Numpy

at_cholesky_vectorized = at.linalg.cholesky(A2).eval()
numpy_cholesky = np.linalg.cholesky(A2).astype(A2.dtype)

np.allclose(at_cholesky_vectorized, numpy_cholesky)

NP Vectorize...


False

In [14]:
# Aesara scipy with vectorization vs Scipy

at_cholesky_vectorized = at.linalg.cholesky(A2).eval()
scipy_cholesky = scipy.linalg.cholesky(A2, lower=True).astype(A2.dtype)

np.allclose(at_cholesky_vectorized, scipy_cholesky)

NP Vectorize...


False

In [15]:
# Aesara Numpy inplementation vs Numpy

at_cholesky_np = at.linalg.cholesky_np(A2).eval()
numpy_cholesky = np.linalg.cholesky(A2).astype(A2.dtype)

np.allclose(at_cholesky_np, numpy_cholesky)

True

In [16]:
# Aesara Numpy inplementation vs Scipy

at_cholesky_np = at.linalg.cholesky_np(A2).eval()
scipy_cholesky = scipy.linalg.cholesky(A2, lower=True).astype(A2.dtype)

np.allclose(at_cholesky_np, scipy_cholesky)

True