In [1]:
import aesara
from aesara.graph.basic import Apply
from aesara.graph.op import Op
from aesara.tensor.type import TensorType

WARN: Could not locate executable g77
WARN: Could not locate executable f77
WARN: Could not locate executable ifort
WARN: Could not locate executable ifl
WARN: Could not locate executable f90
WARN: Could not locate executable DF
WARN: Could not locate executable efl


In [2]:
import numpy as np

In [3]:
d2_data = np.arange(3*4).reshape(3, 4)

In [4]:
d2_data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
d3_data = np.arange(3*4*5).reshape(3, 4, 5)
d3_data

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [42]:
from aesara.tensor.basic import (
    arange,
    as_tensor_variable,
    concatenate,
    extract_diag,
    full,
    mgrid,
    swapaxes,
    switch,
    zeros,
    zeros_like,
)
from aesara.tensor.subtensor import set_subtensor

In [9]:
zeros_like(d2_data).eval()

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
d2_data.shape

(3, 4)

In [12]:
d2_data.shape[-1]

4

In [20]:
slice(10, 20, 30)

slice(10, 20, 30)

In [22]:
slice(10, 20)

slice(10, 20, None)

In [23]:
slice(10)

slice(None, 10, None)

In [24]:
slice(d2_data.shape[-1]), slice(d2_data.shape[-1])

(slice(None, 4, None), slice(None, 4, None))

In [30]:
s = d2_data

In [31]:
inds0, inds1 = mgrid[slice(s.shape[-1]), slice(s.shape[-1])]

In [33]:
inds0

Elemwise{mul,no_inplace}.0

In [34]:
inds0.eval()

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]], dtype=int64)

In [35]:
inds1.eval()

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

In [37]:
(inds1 <= inds0).eval()

array([[ True, False, False, False],
       [ True,  True, False, False],
       [ True,  True,  True, False],
       [ True,  True,  True,  True]])

In [39]:
tril_inds = full(s.shape, inds1 <= inds0)
tril_inds.eval()

ERROR (aesara.graph.opt): Optimization failure due to: constant_folding
ERROR (aesara.graph.opt): node: Assert{msg=Shapes must be equal}(TensorConstant{[[ True Fa..ue  True]]}, TensorConstant{False})
ERROR (aesara.graph.opt): TRACEBACK:
ERROR (aesara.graph.opt): Traceback (most recent call last):
  File "D:\OpenSource\aesara\aesara\graph\opt.py", line 1861, in process_node
    replacements = lopt.transform(fgraph, node)
  File "D:\OpenSource\aesara\aesara\graph\opt.py", line 1066, in transform
    return self.fn(fgraph, node)
  File "D:\OpenSource\aesara\aesara\tensor\basic_opt.py", line 2868, in constant_folding
    required = thunk()
  File "D:\OpenSource\aesara\aesara\link\c\op.py", line 103, in rval
    thunk()
  File "D:\OpenSource\aesara\aesara\link\c\basic.py", line 1769, in __call__
    raise exc_value.with_traceback(exc_trace)
AssertionError: Shapes must be equal



AssertionError: Shapes must be equal

In [ ]:
set_subtensor(output[tril_inds], s[tril_inds])

In [48]:
def tril(s):
    output = zeros_like(s)
    inds0, inds1 = mgrid[slice(s.shape[-1]), slice(s.shape[-1])]
    tril_inds = full(s.shape, inds1 <= inds0)
    return set_subtensor(output[tril_inds], s[tril_inds])

In [49]:
tril(d3_data)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [45]:
tril_inds

Alloc.0