In [1]:
import numpy as np
import aesara.tensor as at

WARN: Could not locate executable g77
WARN: Could not locate executable f77
WARN: Could not locate executable ifort
WARN: Could not locate executable ifl
WARN: Could not locate executable f90
WARN: Could not locate executable DF
WARN: Could not locate executable efl


In [2]:
np.tri(3, 5, 2, dtype=int)

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [3]:
at.tri(3, 5, 2, dtype=int)

Tri{dtype=<class 'int'>}.0

In [4]:
at.tri(3, 5, 2, dtype=int).eval()

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [11]:
x = np.arange(3*4).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
mask = at.tri(*x.shape[-2:], 0, dtype=int).eval()
mask

array([[1, 0, 0, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 0]])

In [12]:
x * mask

array([[ 0,  0,  0,  0],
       [ 4,  5,  0,  0],
       [ 8,  9, 10,  0]])

In [14]:
y = np.arange(2*3*4).reshape(2, 3, 4)
y

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [15]:
y * mask

array([[[ 0,  0,  0,  0],
        [ 4,  5,  0,  0],
        [ 8,  9, 10,  0]],

       [[12,  0,  0,  0],
        [16, 17,  0,  0],
        [20, 21, 22,  0]]])

In [16]:
y = np.arange(3*4*5).reshape(3, 4, 5)
y

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [19]:
mask = at.tri(*y.shape[-2:], 0, dtype=int)
mask

Tri{dtype=<class 'int'>}.0

In [22]:
(y*mask).eval()

array([[[ 0,  0,  0,  0,  0],
        [ 5,  6,  0,  0,  0],
        [10, 11, 12,  0,  0],
        [15, 16, 17, 18,  0]],

       [[20,  0,  0,  0,  0],
        [25, 26,  0,  0,  0],
        [30, 31, 32,  0,  0],
        [35, 36, 37, 38,  0]],

       [[40,  0,  0,  0,  0],
        [45, 46,  0,  0,  0],
        [50, 51, 52,  0,  0],
        [55, 56, 57, 58,  0]]])