## Defining data

In [2]:
d2_data = np.arange(3*4).reshape(3,4)
d2_data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
d3_data = np.arange(3*4*5).reshape(3,4,5)
d3_data

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [4]:
d4_data = np.arange(2*3*4*5).reshape(2,3,4,5)
d4_data

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

## Numpy Tril Method

In [6]:
# for 2D Data
np.tril(d2_data)

array([[ 0,  0,  0,  0],
       [ 4,  5,  0,  0],
       [ 8,  9, 10,  0]])

In [7]:
# for 3D Data
np.tril(d3_data)

array([[[ 0,  0,  0,  0,  0],
        [ 5,  6,  0,  0,  0],
        [10, 11, 12,  0,  0],
        [15, 16, 17, 18,  0]],

       [[20,  0,  0,  0,  0],
        [25, 26,  0,  0,  0],
        [30, 31, 32,  0,  0],
        [35, 36, 37, 38,  0]],

       [[40,  0,  0,  0,  0],
        [45, 46,  0,  0,  0],
        [50, 51, 52,  0,  0],
        [55, 56, 57, 58,  0]]])

In [8]:
# for 4D Data
np.tril(d4_data)

array([[[[  0,   0,   0,   0,   0],
         [  5,   6,   0,   0,   0],
         [ 10,  11,  12,   0,   0],
         [ 15,  16,  17,  18,   0]],

        [[ 20,   0,   0,   0,   0],
         [ 25,  26,   0,   0,   0],
         [ 30,  31,  32,   0,   0],
         [ 35,  36,  37,  38,   0]],

        [[ 40,   0,   0,   0,   0],
         [ 45,  46,   0,   0,   0],
         [ 50,  51,  52,   0,   0],
         [ 55,  56,  57,  58,   0]]],


       [[[ 60,   0,   0,   0,   0],
         [ 65,  66,   0,   0,   0],
         [ 70,  71,  72,   0,   0],
         [ 75,  76,  77,  78,   0]],

        [[ 80,   0,   0,   0,   0],
         [ 85,  86,   0,   0,   0],
         [ 90,  91,  92,   0,   0],
         [ 95,  96,  97,  98,   0]],

        [[100,   0,   0,   0,   0],
         [105, 106,   0,   0,   0],
         [110, 111, 112,   0,   0],
         [115, 116, 117, 118,   0]]]])

## Aesara Tril - Before

In [1]:
import numpy as np
import aesara.tensor as at

WARN: Could not locate executable g77
WARN: Could not locate executable f77
WARN: Could not locate executable ifort
WARN: Could not locate executable ifl
WARN: Could not locate executable f90
WARN: Could not locate executable DF
WARN: Could not locate executable efl


In [6]:
at.tril(d2_data).eval()

array([[ 0,  0,  0,  0],
       [ 4,  5,  0,  0],
       [ 8,  9, 10,  0]])

In [7]:
at.tril(d3_data).eval()

ERROR (aesara.graph.opt): Optimization failure due to: constant_folding
ERROR (aesara.graph.opt): node: Elemwise{mul,no_inplace}(TensorConstant{[[[ 0  1  ..7 58 59]]]}, TensorConstant{[[[1 0 0 0..1 1 1 0]]]})
ERROR (aesara.graph.opt): TRACEBACK:
ERROR (aesara.graph.opt): Traceback (most recent call last):
  File "D:\OpenSource\aesara\aesara\graph\opt.py", line 1861, in process_node
    replacements = lopt.transform(fgraph, node)
  File "D:\OpenSource\aesara\aesara\graph\opt.py", line 1066, in transform
    return self.fn(fgraph, node)
  File "D:\OpenSource\aesara\aesara\tensor\basic_opt.py", line 2868, in constant_folding
    required = thunk()
  File "D:\OpenSource\aesara\aesara\link\c\op.py", line 103, in rval
    thunk()
  File "D:\OpenSource\aesara\aesara\link\c\basic.py", line 1769, in __call__
    raise exc_value.with_traceback(exc_trace)
ValueError: Input dimension mismatch. One other input has shape[1] = 4, but input[1].shape[1] = 3.

ERROR (aesara.graph.opt): Optimization fail

ValueError: Input dimension mismatch. One other input has shape[1] = 4, but input[1].shape[1] = 3.
Apply node that caused the error: Elemwise{mul,no_inplace}(TensorConstant{[[[ 0  1  ..7 58 59]]]}, TensorConstant{[[[1 0 0 0..1 1 1 0]]]})
Toposort index: 0
Inputs types: [TensorType(int32, (3, 4, 5)), TensorType(int32, (1, 3, 4))]
Inputs shapes: [(3, 4, 5), (1, 3, 4)]
Inputs strides: [(80, 20, 4), (48, 16, 4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [['output']]

Backtrace when the node is created (use Aesara flag traceback__limit=N to make it longer):
  File "C:\Users\Purna\anaconda3\envs\aesara-dev\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\Purna\anaconda3\envs\aesara-dev\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_cell
    result = self._run_cell(
  File "C:\Users\Purna\anaconda3\envs\aesara-dev\lib\site-packages\IPython\core\interactiveshell.py", line 2936, in _run_cell
    return runner(coro)
  File "C:\Users\Purna\anaconda3\envs\aesara-dev\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\Purna\anaconda3\envs\aesara-dev\lib\site-packages\IPython\core\interactiveshell.py", line 3135, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\Purna\anaconda3\envs\aesara-dev\lib\site-packages\IPython\core\interactiveshell.py", line 3338, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\Purna\anaconda3\envs\aesara-dev\lib\site-packages\IPython\core\interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Purna\AppData\Local\Temp\ipykernel_5944\3809819310.py", line 1, in <cell line: 1>
    at.tril(d3_data).eval()

HINT: Use the Aesara flag `exception_verbosity=high` for a debug print-out and storage map footprint of this Apply node.

## Aesara Tril - After

In [1]:
import numpy as np
import aesara.tensor as at

WARN: Could not locate executable g77
WARN: Could not locate executable f77
WARN: Could not locate executable ifort
WARN: Could not locate executable ifl
WARN: Could not locate executable f90
WARN: Could not locate executable DF
WARN: Could not locate executable efl


In [10]:
# for 2D Data
at.tril(d2_data).eval()

PRINTING JUST TO CHECK THIS LINE IS EXECUTING :) :) :)


array([[ 0,  0,  0,  0],
       [ 4,  5,  0,  0],
       [ 8,  9, 10,  0]])

In [11]:
# for 3D Data
at.tril(d3_data).eval()

PRINTING JUST TO CHECK THIS LINE IS EXECUTING :) :) :)


array([[[ 0,  0,  0,  0,  0],
        [ 5,  6,  0,  0,  0],
        [10, 11, 12,  0,  0],
        [15, 16, 17, 18,  0]],

       [[20,  0,  0,  0,  0],
        [25, 26,  0,  0,  0],
        [30, 31, 32,  0,  0],
        [35, 36, 37, 38,  0]],

       [[40,  0,  0,  0,  0],
        [45, 46,  0,  0,  0],
        [50, 51, 52,  0,  0],
        [55, 56, 57, 58,  0]]])

In [12]:
# for 4D Data
at.tril(d4_data).eval()

PRINTING JUST TO CHECK THIS LINE IS EXECUTING :) :) :)


array([[[[  0,   0,   0,   0,   0],
         [  5,   6,   0,   0,   0],
         [ 10,  11,  12,   0,   0],
         [ 15,  16,  17,  18,   0]],

        [[ 20,   0,   0,   0,   0],
         [ 25,  26,   0,   0,   0],
         [ 30,  31,  32,   0,   0],
         [ 35,  36,  37,  38,   0]],

        [[ 40,   0,   0,   0,   0],
         [ 45,  46,   0,   0,   0],
         [ 50,  51,  52,   0,   0],
         [ 55,  56,  57,  58,   0]]],


       [[[ 60,   0,   0,   0,   0],
         [ 65,  66,   0,   0,   0],
         [ 70,  71,  72,   0,   0],
         [ 75,  76,  77,  78,   0]],

        [[ 80,   0,   0,   0,   0],
         [ 85,  86,   0,   0,   0],
         [ 90,  91,  92,   0,   0],
         [ 95,  96,  97,  98,   0]],

        [[100,   0,   0,   0,   0],
         [105, 106,   0,   0,   0],
         [110, 111, 112,   0,   0],
         [115, 116, 117, 118,   0]]]])